version: "3"

services:
  code-server:
    container_name: code-server
    image: cavalrytactics/code-server:latest
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}:/home/coder/project"
      - "${PWD}/dev-env/code-server:/home/coder/.local/share/code-server"
      - "${PWD}/dev-env/oh-my-zsh/.zshrc:/home/coder/.zshrc"
    entrypoint:
      - dumb-init
      - code-server
      - --auth=none
      - --disable-telemetry
